version: '3'
services:
  web:
    build: .
    command: sh -c 'sleep 10 && python3 manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/hamrohouse
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root1234
      
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5100:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
volumes:
  postgres_data:
